#!/bin/bash

cd "$(dirname "$0")"

if (source venv/bin/activate) ; then
		source venv/bin/activate
		echo "venv installed 👍"
else 
		python3 -m venv venv 
		source venv/bin/activate
		pip install -r requirements.txt
fi

python3 bot.py