#!/bin/bash

cd "$(dirname "$0")"
 
read -p 'commit name: ' commit

if [ -z "$commit" ]
then
    commit="autosave"
fi
git commit -am $commit

output=$(git remote)
pusharray=($output)

for i in ${pusharray[@]}; do
    git push $i master
done

